[project]
name = "ia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pgmpy>=1.0.0",
    "pyparsing>=3.2.3",
    "scipy==1.15.3",
]
